name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  productNamespacePrefix: "ReactiveMvvm"

jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Java JDK 11'
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'microsoft'
          java-version: '11'
      
      - name: 'Install DotNet workloads'
        shell: bash
        run: |
          dotnet workload install android ios tvos macos maui maccatalyst wasm-tools-net7 

      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run: RunInteractive'
        run: ./build.cmd RunInteractive
